version: 2
jobs:
  build:
    docker:
      - image: "circleci/php:7.1-cli-jessie-node-browsers-legacy"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "src/__fixtures__/composer.json" }}
            - v2-dependencies-
      - run:
          name: install
          command: |
            npm install
            npm run test:install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - src/__fixtures__/vendor
          key: v2-dependencies-{{ checksum "src/__fixtures__/composer.json" }}
      - run:
          name: release
          command: npm run semantic-release || true
      - run:
          name: coverage
          command: npm run ci:coverage
